"Campo Grande","MS","NTAwMjAwNDAyNzA0"
"Crateus","CE","MjMwNDAxODA0MTAz"
"Sao Paulo","SP","MzUxNTA2MTUwMzA4"
"Rio Branco","AC","MTIwMjAwNDAwNDAx"
"Presidente Prudente","SP","MzUwODAzNjQxNDA2"
"Marilia","SP","MzUwOTAzODI5MDA1"
"Sao Joao Del Rei","MG","MzExMTA1ODYyNTAw"
"Cuiaba","MT","NTEwNDAxNzAzNDAz"
"Lauro de Freitas","BA","MjkwNTAyMTE5MjA3"
"Itaperuna","RJ","MzMwMTAwMTAyMjA1"
"Salvador","BA","MjkwNTAyMTI3NDA4"
"Rio Claro","SP","MzUwNjAyNjQzOTA3"
"Belem","PA","MTUwMzAwNzAxNDAy"
"Curitiba","PR","NDExMDAzNzA2OTAy"
"Parnaiba","PI","MjIwMTAwMjA3NzAy"
"Joao Pessoa","PB","MjUwNDAyMjA3NTA3"
"Caxias do Sul","RS","NDMwMjAxNjA1MTA4"
"Imperatriz","MA","MjEwMjAwOTA1MzAy"
"Sao Luis","MA","MjEwMTAwMjExMzAw"
"Vespasiano","MG","MzEwNzAzMDcxMjA0"
"Juiz de Fora","MG","MzExMjA2NTM2NzAy"
"Campinas","SP","MzUwNzAzMjA5NTAy"
"Jacobina","BA","MjkwMzAxMDE3NTA4"
"Belo Horizonte","MG","MzEwNzAzMDA2MjAw"
"Muriae","MG","MzExMjA2MzQzOTA2"
"Sao Jose dos Campos","SP","MzUxMzA1MDQ5OTA0"
"Maringa","PR","NDEwMzAwOTE1MjAw"
"Fernandopolis","SP","MzUwMTAwMjE1NTA5"
"Ipatinga","MG","MzEwODAzOTMxMzA3"
"Palmas","TO","MTcwMjAwNjIxMDAw"
"Araguaina","TO","MTcwMTAwMjAyMTA5"
"Fortaleza","CE","MjMwMzAxNjA0NDAw"
"Ribeirao Preto","SP","MzUwMjAxNDQzNDAy"
"Campo Mourao","PR","NDEwMjAwNTA0MzAz"
"Campina Grande","PB","MjUwMzAxNzA0MDA5"
"Teresopolis","RJ","MzMwNjAxNTA1ODAy"
"Uba","MG","MzExMjA2NDY5OTAx"
"Passo Fundo","RS","NDMwMTAxMDE0MTAw"
"Londrina","PR","NDEwMzAxMTEzNzAw"
"Betim","MG","MzEwNzAzMDA2NzA1"
"Porto Alegre","RS","NDMwNTAyNjE0OTAy"
"Caratinga","MG","MzEwODA0MDEzNDA0"
"Barreiras","BA","MjkwMTAwMTAzMjAx"
"Porto Nacional","TO","MTcwMjAwNjE4MjA0"
"Mogi das Cruzes","SP","MzUxNTA2MjMwNjA3"
"Uberaba","MG","MzEwNTAyMjcwMTA3"
"Barbacena","MG","MzExMTA1OTA1NjA4"
"Canoas","RS","NDMwNTAyNjA0NjA2"
"Ponte Nova","MG","MzExMjA2MDUyMTA1"
"Maceio","AL","MjcwMzAxMTA0MzAy"
"Olinda","PE","MjYwNTAxNzA5NjAw"
"Paracatu","MG","MzEwMTAwMjQ3MDA2"
"Pato Branco","PR","NDEwNzAyNzE4NTAx"
"Franca","SP","MzUwMjAxMjE2MjAw"
"Vitoria da Conquista","BA","MjkwNjAyODMzMzA3"
"Pocos de Caldas","MG","MzExMDA1MTUxODAw"
"Patos","PB","MjUwMTAwNDEwODA4"
"Governador Valadares","MG","MzEwODAzNzI3NzAx"
"Alfenas","MG","MzExMDA0OTAxNjA3"
"Sao Leopoldo","RS","NDMwNTAyNjE4NzA1"
"Montes Claros","MG","MzEwMjAwNzQzMzAy"
"Vassouras","RJ","MzMwNjAxNDA2MjA2"
"Sorocaba","SP","MzUxMjA0NjUyMjA1"
"Petropolis","RJ","MzMwNjAxNTAzOTA2"
"Rio do Sul","SC","NDIwNDAxMTE0ODA1"
"Porto Velho","RO","MTEwMTAwMTAwMjA1"
"Manhuacu","MG","MzExMjA2MTM5NDA5"
"Brasilia","DF","NTMwMTAwMTAwMTA4"
"Teresina","PI","MjIwMjAwMzExMDAx"
"Joinville","SC","NDIwMjAwODA5MTAy"
"Cacoal","RO","MTEwMjAwNjAwMDQ5"
"Natal","RN","MjQwNDAxODA4MTAy"
"Patos de Minas","MG","MzEwNTAyMDQ4MDA0"
"Aracaju","SE","MjgwMzAxMTAwMzA4"
"Goiania","GO","NTIwMzAxMDA4NzA3"
"Mineiros","GO","NTIwNTAxMzEzMTAz"
"Santa Cruz do Sul","RS","NDMwNDAyMDE2ODA4"
"Recife","PE","MjYwNTAxNzExNjA2"
"Guarapuava","PR","NDEwODAyOTA5NDAx"
"Palhoca","SC","NDIwNTAxNjExOTAw"
"Guanambi","BA","MjkwNjAyNjExNzA5"
"Catanduva","SP","MzUwMTAwNTExMTAy"
"Erechim","RS","NDMwMTAwNDA3MDA1"
"Valenca","RJ","MzMwNTAxMjA2MTA3"
"Pouso Alegre","MG","MzExMDA1MjUyNTAx"
"Colatina","ES","MzIwMTAwMzAxNTA2"
"Santos","SP","MzUxNTA2MzQ4NTAw"
"Vitoria","ES","MzIwMzAwOTA1MzA5"
"Vila Velha","ES","MzIwMzAwOTA1MjAw"
"Braganca Paulista","SP","MzUxMjA0ODA3NjA1"
"Santa Maria","RS","NDMwMzAxODE2OTA3"
"Pelotas","RS","NDMwNzAzMzE0NDA3"
"Araraquara","SP","MzUwNTAyNDAzMjA4"
"Tubarao","SC","NDIwNjAxODE4NzA3"
"Roseira","SP","MzUxMzA1MTQ0MzAx"
"Criciuma","SC","NDIwNjAxOTA0NjA4"
"Itauna","MG","MzEwOTA0MzMzODA4"
"Novo Hamburgo","RS","NDMwNTAyNjEzNDA5"
"Anapolis","GO","NTIwMzAwNzAxMTA4"
"Cajazeiras","PB","MjUwMTAwMjAzNzA0"
"Itajai","SC","NDIwNDAxMzA4MjAz"
"Joacaba","SC","NDIwMTAwNDA5MDAz"
"Cafelandia","PR","NDEwNjAyMzAzNDUz"
"Rio de Janeiro","RJ","MzMwNjAxODA0NTU3"
"Sinop","MT","NTEwMTAwNzA3OTA5"
"Macapa","AP","MTYwMjAwMzAwMzAz"
"Cascavel","PR","NDEwNjAyMzA0ODA4"
"Francisco Beltrao","PR","NDEwNzAyNjA4NDAz"
"Umuarama","PR","NDEwMTAwMjI4MTA0"
"Balneario Camboriu","SC","NDIwNDAxMzAyMDA4"
"Trindade","GO","NTIwMzAxMDIxNDAz"
"Jaragua do Sul","SC","NDIwMjAwODA4OTA2"
"Caucaia","CE","MjMwMzAxNjAzNzA5"
"Santo Angelo","RS","NDMwMTAwNzE3NTA5"
"Toledo","PR","NDEwNjAyMjI3NzAw"
"Foz do Iguacu","PR","NDEwNjAyNDA4MzA0"
"Paripiranga","BA","MjkwNDAxNTIzODAz"
"Ponta Grossa","PR","NDEwNTAyMTE5OTA1"
"Mossoro","RN","MjQwMTAwMTA4MDAz"
"Alagoinhas","BA","MjkwNDAxNzAwNzAy"
"Lavras","MG","MzExMTA1NzM4MjAz"
"Mato Verde","MG","MzEwMjAwNDQxMDA5"
"Barretos","SP","MzUwMjAwOTA1NTAw"
"Ijui","RS","NDMwMTAwODEwMjA3"
"Juazeiro do Norte","CE","MjMwNzAzMjA3MzA0"
"Santa Teresa","ES","MzIwMzAwODA0NjA5"
"Cachoeira","BA","MjkwNTAyMDA0OTAy"
"Bento Goncalves","RS","NDMwMjAxNjAyMTA1"
"Niteroi","RJ","MzMwNjAxODAzMzAy"
"Chapeco","SC","NDIwMTAwMjA0MjAy"
"Tangara da Serra","MT","NTEwMzAxMzA3OTU4"
"Caceres","MT","NTEwNDAxODAyNTA0"
"Bauru","SP","MzUwNDAyMDA2MDAz"
"Sao Bernardo do Campo","SP","MzUxNTA2MTQ4NzA4"
"Ji-Parana","RO","MTEwMjAwNDAwMTIy"
"Petrolina","PE","MjYwMjAwNTExMTAx"
"Lages","SC","NDIwMzAxMDA5MzAw"
"Campos Novos","SC","NDIwMzAwOTAzNjAw"
"Sao Miguel do Oeste","SC","NDIwMTAwMTE3MjA0"
"Xanxere","SC","NDIwMTAwMzE5NTA3"
"Cruz Alta","RS","NDMwMTAxMTA2MTA2"
"Alegrete","RS","NDMwNjAyOTAwNDA2"
"Bage","RS","NDMwNjAzMTAxNjAy"
"Aguas de Sao Pedro","SP","MzUwNjAyODAwNjAw"
"Campos do Jordao","SP","MzUxMzA0OTA5NzAw"
"Frederico Westphalen","RS","NDMwMTAwMzA4NTA4"
"Araras","SP","MzUwNjAyNzAzMzA3"
"Guaranta do Norte","MT","NTEwMTAwMzA0MTA0"
"Ituverava","SP","MzUwMjAxMTI0MTA1"
"Juazeiro","BA","MjkwMjAwNDE4NDA3"
"Itabuna","BA","MjkwNzAzMTE0ODAy"
"Caruaru","PE","MjYwMzAwODA0MTA2"
"Linhares","ES","MzIwMjAwNjAzMjA1"
"Jaguariuna","SP","MzUwNzAzMjI0NzA5"
"Irece","BA","MjkwMzAwOTE0NjA0"
"Guarapari","ES","MzIwMzAxMDAyNDA1"
"Rondonopolis","MT","NTEwNTAyMTA3NjAy"
"Quixada","CE","MjMwNDAxOTExMzA2"
"Manaus","AM","MTMwMzAwNzAyNjAz"
"Varginha","MG","MzExMDA1MDcwNzAx"
"Barueri","SP","MzUxNTA1NzA1NzA4"
"Itaborai","RJ","MzMwNjAxODAxOTAw"
"Sete Lagoas","MG","MzEwNzAyNzY3MjAy"
"Indaiatuba","SP","MzUwNzAzMjIwNTA5"
"Osorio","RS","NDMwNTAyNzEzNTA4"
"Nova Venecia","ES","MzIwMTAwMjAzOTA4"
"Arapongas","PR","NDEwMzAxMDAxNTA3"
"Santo Andre","SP","MzUxNTA2MTQ3ODA5"
"Unai","MG","MzEwMTAwMTcwNDA0"
"Cabedelo","PB","MjUwNDAyMjAzMjA5"
"Vitoria de Santo Antao","PE","MjYwNDAxNDE2NDA3"
"Avare","SP","MzUwNDAyMjA0NTAz"
"Valparaiso de Goias","GO","NTIwNDAxMjIxODU4"
"Ilheus","BA","MjkwNzAzMTEzNjA2"
"Santa Rosa","RS","NDMwMTAwMTE3MjAy"
"Feira de Santana","BA","MjkwMzAxMjEwODAw"
"Jequie","BA","MjkwNjAyNDE4MDAx"
"Luziania","GO","NTIwNDAxMjEyNTAx"
"Leme","SP","MzUwNjAyNzI2NzA0"
"Nova Lima","MG","MzEwNzAzMDQ0ODA1"
"Serra Talhada","PE","MjYwMTAwMzEzOTA5"
"Orleans","SC","NDIwNjAxODExNzAy"
"Floriano","PI","MjIwMzAwOTAzOTA5"
"Panambi","RS","NDMwMTAwODEzOTA0"
"Matipo","MG","MzExMjA2MTQwOTAy"
"Blumenau","SC","NDIwNDAxMjAyNDA0"
"Florianopolis","SC","NDIwNTAxNjA1NDA3"
"Sao Bento do Sul","SC","NDIwMjAwNzE1ODAy"
"Caxias","MA","MjEwNDAxNzAzMDAw"
"Sao Jose do Rio Preto","SP","MzUwMTAwNDQ5ODA1"
"Getulio Vargas","RS","NDMwMTAwNDA4OTA0"
"Vicosa","MG","MzExMjA2MjcxMzAz"
"Sao Carlos","SP","MzUwNTAyNTQ4OTA2"
"Cruz das Almas","BA","MjkwNTAyMDA5ODAy"
"Carazinho","RS","NDMwMTAwOTA0NzA1"
"Dourados","MS","NTAwNDAxMDAzNzAy"
"Teofilo Otoni","MG","MzEwNDAxNTY4NjA2"
"Juina","MT","NTEwMTAwMTA1MTUw"
"Sao Jose","SC","NDIwNTAxNjE2NjAy"
"Itajuba","MG","MzExMDA1NjMyNDA0"
"Arapiraca","AL","MjcwMjAwNjAwMzAw"
"Dois VIzinhos","PR","NDEwNzAyNjA3MjA3"
"Cabo Frio","RJ","MzMwNDAxMDAwNzA0"
"Uberlandia","MG","MzEwNTAxODcwMjA2"
"Tres de Maio","RS","NDMwMTAwMTIxODA4"
"Cachoeira do Sul","RS","NDMwNDAyMjAzMDA0"
"Vacaria","RS","NDMwMjAxNTIyNTA5"
"Bom Despacho","MG","MzEwNjAyNjA3NDA2"
"Salto","SP","MzUxMjA0NjQ1MjA5"
"Horizontina","RS","NDMwMTAwMjA5NjA1"
"Rolandia","PR","NDEwMzAxMTIyNDA0"
"Santiago","RS","NDMwMzAxNzE3NDAw"
"Osasco","SP","MzUxNTA1NzM0NDAx"
"Juara","MT","NTEwMTAwNTA1MTAx"
"Sao Joao da Boa VIsta","SP","MzUwNzAzMDQ5MTAy"
"Contagem","MG","MzEwNzAzMDE4NjAx"
"Tres Passos","RS","NDMwMTAwMjIxOTA3"
"Castanhal","PA","MTUwMzAwODAyNDAw"
"Telemaco Borba","PR","NDEwNTAxOTI3MTA2"
"Vilhena","RO","MTEwMjAwNzAwMzA0"
"Santana do Livramento","RS","NDMwNjAzMDE3MTAz"
"Sao Gabriel","RS","NDMwNjAzMDE4MzA5"
"Farroupilha","RS","NDMwMjAxNjA3OTA2"
"Sao Jeronimo","RS","NDMwNTAyNTE4NDA4"
"Itapiranga","SC","NDIwMTAwMTA4NDAx"
"Concordia","SC","NDIwMTAwNTA0MzAx"
"Gravatai","RS","NDMwNTAyNjA5MjA5"
"Guarulhos","SP","MzUxNTA1OTE4ODAw"
"Uniao da VItoria","PR","NDEwOTAzMzI4MjAz"
"Descalvado","SP","MzUwNTAyNTEzNzAy"
"Cianorte","PR","NDEwMTAwMzA1NTA4"
"Paranavai","PR","NDEwMTAwMTE4NDAy"
"Sao Luiz Gonzaga","RS","NDMwMTAwNzE4OTAz"
"Campo Largo","PR","NDExMDAzNzA0MjA0"
"Sarandi","RS","NDMwMTAwOTIwMTA3"
"Ariquemes","RO","MTEwMjAwMzAwMDIz"
"Marau","RS","NDMwMTAxMDExODA5"
"Sao Sebastiao do Paraiso","MG","MzExMDA0ODY0NzA0"
"Restinga Seca","RS","NDMwMzAxOTE1NTAz"
"Boa VIsta","RR","MTQwMTAwMTAwMTAw"
"Barra do Garcas","MT","NTEwMjAxMTAxODAz"
"Itabira","MG","MzEwNzAzMTMxNzAz"
"Itapeva","SP","MzUxMTA0MTIyNDA2"
"Primavera do Leste","MT","NTEwNTAxOTA3MDQw"
"Coromandel","MG","MzEwNTAxOTE5MzAy"
"Videira","SC","NDIwMTAwNDE5MzA5"
"Lencois Paulista","SP","MzUwNDAyMDI2ODAz"
"Torres","RS","NDMwNTAyNzIxNTAx"
"Araucaria","PR","NDExMDAzNzAxODA0"
"Pitanga","PR","NDEwODAyODE5NjA4"
"Garibaldi","RS","NDMwMjAxNjA4NjA3"
"Guaira","PR","NDEwNjAyMjA4ODA5"
"Tres Lagoas","MS","NTAwMzAwNzA4MzA1"
"Americana","SP","MzUwNzAzMjAxNjA4"
"Ivatuba","PR","NDEwMzAwODExNjA1"
"Patrocinio","MG","MzEwNTAxOTQ4MTAz"
"Guaiba","RS","NDMwNTAyNjA5MzA4"
"Maraba","PA","MTUwNjAyMDA0MjA4"
"Cerro Largo","RS","NDMwMTAwNjA1MjA3"
"Lins","SP","MzUwNDAxOTI3MTA4"
"Itumbiara","GO","NTIwNTAxNTExNTAz"
"Limeira","SP","MzUwNjAyNzI2OTAy"
"Castelo","ES","MzIwNDAxMjAxNDA3"
"Redencao","PA","MTUwNjAyMTA2MTM4"
"Serra","ES","MzIwMzAwOTA1MDAy"
"Conselheiro Lafaiete","MG","MzEwNzAzNDE4MzA0"
"Coronel Fabriciano","MG","MzEwODAzOTE5NDAx"
"Itatiba","SP","MzUxMjA0ODIzNDA0"
"Soledade","RS","NDMwMTAxMzIwODAw"
"Lucas do Rio Verde","MT","NTEwMTAwNjA1MjU5"
"Araguari","MG","MzEwNTAxODAzNTA0"
"Divinopolis","MG","MzEwOTA0MzIyMzA2"
"Sorriso","MT","NTEwMTAwNjA3OTI1"
"Tupa","SP","MzUwOTAzNzU1MDAw"
"Jundiai","SP","MzUxMjA0NzI1OTA0"
"Aimores","MG","MzEwODA0MTAxMTAy"
"Rio Grande","RS","NDMwNzAzNTE1NjAy"
"Aparecida de Goiania","GO","NTIwMzAxMDAxNDA1"
"Sao Francisco do Sul","SC","NDIwMjAwODE2MjA2"
"Sao Mateus","ES","MzIwMjAwNTA0OTA2"
"Guarai","TO","MTcwMTAwMzA5MzAy"
"Aracatuba","SP","MzUwMzAxNzAyODA0"
"Jaboatao dos Guararapes","PE","MjYwNTAxNzA3OTAx"
"Tiangua","CE","MjMwMTAwMjEzNDAx"
"Garca","SP","MzUwOTAzODE2NzA1"
"Catalao","GO","NTIwNTAxNzA1MTA5"
"Santa Rita do Sapucai","MG","MzExMDA1MzU5NjA1"
"Xaxim","SC","NDIwMTAwMzE5NzA1"
"Capivari de Baixo","SC","NDIwNjAxODAzOTU2"
"Assis Chateaubriand","PR","NDEwNjAyMjAyMDAw"
"Santo Antonio de Jesus","BA","MjkwNTAyMDI4NzAz"
"Casca","RS","NDMwMTAxMDA0OTAz"
"Lagoa Vermelha","RS","NDMwMjAxNTExMzA0"
"Ipora","GO","NTIwMzAwODEwMjA4"
"Biguacu","SC","NDIwNTAxNjAyMzA1"
"Tijucas","SC","NDIwNTAxNTE4MDA0"
"Rolim de Moura","RO","MTEwMjAwNjAwMjg4"
"Registro","SP","MzUxNDA1NTQyNjAy"
"Senhor do Bonfim","BA","MjkwMzAwODMwMTA1"
"Lagarto","SE","MjgwMjAwNjAzNTAw"
"Curvelo","MG","MzEwNjAyNTIwOTA0"
"Pinhalzinho","SC","NDIwMTAwMjEyOTA4"
"Atibaia","SP","MzUxMjA0ODA0MTA3"
"Guaratingueta","SP","MzUxMzA1MTE4NDA0"
"Votuporanga","SP","MzUwMTAwMzU3MTA1"
"Nanuque","MG","MzEwNDAxNjQ0MzAw"
"Navegantes","SC","NDIwNDAxMzExMzA2"
"Valenca","BA","MjkwNzAzMDMyOTAz"
"Engenheiro Coelho","SP","MzUwNzAzMTE1MTUy"
"Lorena","SP","MzUxMzA1MTI3MjA3"
"Sao Jose dos Pinhais","PR","NDExMDAzNzI1NTA2"
"Bandeirantes","PR","NDEwNDAxNTAyNDA2"
"Agudos","SP","MzUwNDAyMDAwNzA5"
"Ico","CE","MjMwNjAyNjA1NDA3"
"Aracruz","ES","MzIwMjAwNjAwNjA3"
"Campos dos Goytacazes","RJ","MzMwMjAwMzAxMDA5"
"Leopoldina","MG","MzExMjA2NjM4NDAx"
"Sao Lourenco","MG","MzExMDA1NDYzNzA2"
"Piracicaba","SP","MzUwNjAyODM4NzA5"
"Fazenda Rio Grande","PR","NDExMDAzNzA3NjUy"
"Camacari","BA","MjkwNTAyMTA1NzAx"
"Jaboticabal","SP","MzUwMjAxMzI0MzAz"
"Brumadinho","MG","MzEwNzAzMDA5MDA2"
"Campos Gerais","MG","MzExMDA1MDExNjA2"
"Jaciara","MT","NTEwNTAyMTA0ODA3"
"Paraiba do Sul","RJ","MzMwMzAwNTAzNzA4"
"Queimadas","BA","MjkwNDAxNDI1ODA4"
"Sobradinho","RS","NDMwNDAyMDIwNzAx"
"Venancio Aires","RS","NDMwNDAyMDIyNjA4"
"Tucurui","PA","MTUwNjAxNjA4MTAw"
"Itarare","SP","MzUxMTA0MTIzMjA2"
"Jussara","GO","NTIwMTAwMjEyMjA0"
"Jacarei","SP","MzUxMzA1MDI0NDAy"
"Paulo Afonso","BA","MjkwMjAwNTI0MDA5"
"Janauba","MG","MzEwMjAwNDM1MTAw"
"Guaxupe","MG","MzExMDA0ODI4NzA5"
"Estrela","RS","NDMwNDAyMTA3ODA3"
"Jau","SP","MzUwNDAyMTI1MzAw"
"Ceres","GO","NTIwMzAwNjA1NDA2"
"Goianesia","GO","NTIwMzAwNjA4NjA4"
"Resende","RJ","MzMwNTAxMTA0MjAx"
"Juatuba","MG","MzEwNzAzMDM2NjUy"
"Para de Minas","MG","MzEwNzAyOTQ3MTA1"
"Timbo","SC","NDIwNDAxMjE4MjAy"
"Amparo","SP","MzUwNzAzMzAxOTA1"
"Santarem","PA","MTUwMTAwMjA2ODA3"
"Quixeramobim","CE","MjMwNDAxOTExNDA1"
"Maravilha","SC","NDIwMTAwMjEwNTA2"
"Sao Jose do Cedro","SC","NDIwMTAwMTE2NzAx"
"Cariacica","ES","MzIwMzAwOTAxMzA4"
"Aguas Lindas de Goias","GO","NTIwNDAxMjAwMjU4"
"Teixeira de Freitas","BA","MjkwNzAzMjMxMzUw"
"Santa Maria de Jetiba","ES","MzIwMzAwODA0NTU5"
"Formosa","GO","NTIwNDAxMjA4MDA0"
"Balsas","MA","MjEwNTAyMDAxNDAw"
"Cachoeiro de Itapemirim","ES","MzIwNDAxMjAxMjA5"
"Ivoti","RS","NDMwNTAyNDEwODAx"
"Holambra","SP","MzUwNzAzMjE5MDU1"
"Itabirito","MG","MzEwNzAzMzMxOTAx"
"Nova Porteirinha","MG","MzEwMjAwNDQ1MDU5"
"Bacabal","MA","MjEwMzAxMDAxMjAy"
"Joao Pinheiro","MG","MzEwMTAwMjM2MzA2"
"Santana de Parnaiba","SP","MzUxNTA1NzQ3MzA0"
"Iturama","MG","MzEwNTAyMTM0NDAw"
"Inhumas","GO","NTIwMzAwNzEwMDAw"
"Sao Gotardo","MG","MzEwNTAyMDYyMTA0"
"Marechal Candido Rondon","PR","NDEwNjAyMjE0NjA5"
"Ouro Fino","MG","MzExMDA1MTQ2MDA4"
"Almenara","MG","MzEwMzAxNDAxNzA2"
"Peruibe","SP","MzUxNDA1NjM3NjAy"
"Botucatu","SP","MzUwNDAyMzA3NTA2"
"Sao Jose do Rio Pardo","SP","MzUwNzAzMDQ5NzA2"
"Guaruja","SP","MzUxNTA2MzE4NzAx"
"Cristalina","GO","NTIwNDAxMjA2MjA2"
"Jaguariaiva","PR","NDEwNTAyMDEyMDA5"
"Arcos","MG","MzEwOTA0NDA0MjA1"
"Serro","MG","MzEwNzAyODY3MTAz"
"Quirinopolis","GO","NTIwNTAxODE4NTA4"
"Brusque","SC","NDIwNDAxMjAyOTA5"
"Montenegro","RS","NDMwNTAyMzEyNDAx"
"Aracati","CE","MjMwNTAyMjAxMTA5"
"Paragominas","PA","MTUwNjAxNzA1NTAy"
"Parauapebas","PA","MTUwNjAxOTA1NTM2"
"Ponta Pora","MS","NTAwNDAxMDA2NjA2"
"Diadema","SP","MzUxNTA2MTEzODAx"
"Santa Barbara D`Oeste","SP","MzUwNzAzMjQ1ODAz"
"Guaratuba","PR","NDExMDAzODA5NjA5"
"Ararangua","SC","NDIwNjAyMDAxNDA2"
"Apucarana","PR","NDEwMzAxMDAxNDA4"
"Assis","SP","MzUxMDAzOTA0MDA4"
"Joao Monlevade","MG","MzEwNzAzMTM2MjA3"
"Luis Eduardo Magalhaes","BA","MjkwMTAwMTE5NTUz"
"Sumare","SP","MzUwNzAzMjUyNDAz"
"Belem de Sao Francisco","PE","MjYwMjAwNjAxNjA3"
"Taubate","SP","MzUxMzA1MDU0MTAy"
"Corumba","MS","NTAwMTAwMTAzMjA3"
"Nova Iguacu","RJ","MzMwNjAxODAzNTAw"
"Queimados","RJ","MzMwNjAxODA0MTQ0"
"Volta Redonda","RJ","MzMwNTAxMTA2MzA1"
"Taio","SC","NDIwNDAxMTE3ODA4"
"Itapema","SC","NDIwNDAxMzA4MzAy"
"Cachoeirinha","RS","NDMwNTAyNjAzMTAz"
"Paulista","PE","MjYwNTAxNzEwNzA3"
"Capivari","SP","MzUwNjAyODEwNDAx"
"Sao Miguel do Iguacu","PR","NDEwNjAyNDI1NzA0"
"Praia Grande","SP","MzUxNTA2MzQxMDAw"
"Santo Antonio de Padua","RJ","MzMwMTAwMjA0NzA2"
"Estancia","SE","MjgwMzAxMzAyMTA2"
"Itabaiana","SE","MjgwMjAwNDAyOTA4"
"Votorantim","SP","MzUxMjA0NjU3MDA2"
"Parnamirim","RN","MjQwNDAxODAzMjUx"
"Medianeira","PR","NDEwNjAyNDE1ODA0"
"Sao Fidelis","RJ","MzMwMjAwMzA0ODA1"
"Ribeira do Pombal","BA","MjkwNDAxNTI2NjA4"
"Pau dos Ferros","RN","MjQwMTAwNjA5NDA3"
"Cacapava","SP","MzUxMzA1MDA4NTA0"
"Pimenta Bueno","RO","MTEwMjAwNzAwMTg5"
"Cataguases","MG","MzExMjA2NjE1MzAw"
"Frutal","MG","MzEwNTAyMTI3MTA3"
"Santa Luzia","MG","MzEwNzAzMDU3ODA3"
"Cornelio Procopio","PR","NDEwNDAxNTA2NDA3"
"Ibaiti","PR","NDEwNDAxNzA5NzA4"
"Santo Antonio da Platina","PR","NDEwNDAxNjI0MTAz"
"Duque de Caxias","RJ","MzMwNjAxODAxNzAy"
"Birigui","SP","MzUwMzAxODA2NTA4"
"Boituva","SP","MzUxMTA0MzA3MDAx"
"Caieiras","SP","MzUxNTA1ODA5MDA3"
"Ilha Solteira","SP","MzUwMzAxNjIwNDQy"
"Maua","SP","MzUxNTA2MTI5NDAx"
"Mirassol","SP","MzUwMTAwNDMwMzAw"
"Olimpia","SP","MzUwMTAwNDMzOTA4"
"Presidente Epitacio","SP","MzUwODAzNjQxMzA3"
"Sao Caetano do Sul","SP","MzUxNTA2MTQ4ODA3"
"Sao Roque","SP","MzUxMjA0NjUwNjA1"
"Suzano","SP","MzUxNTA2MjUyNTAy"
"Taquaritinga","SP","MzUwMjAxMzUzNzA4"
"Colinas do Tocantins","TO","MTcwMTAwMjA1NTA4"
"Guarabira","PB","MjUwMzAxNjA2MzAx"
"Sao Goncalo","RJ","MzMwNjAxODA0OTA0"
"Hortolandia","SP","MzUwNzAzMjE5MDcx"
"Jeremoabo","BA","MjkwNDAxMzE4MTAw"
"Tucano","BA","MjkwNDAxNDMxOTA1"
"Visconde do Rio Branco","MG","MzExMjA2NDcyMDA0"
"Tres Rios","RJ","MzMwMzAwNTA2MDA4"
"Pindamonhangaba","SP","MzUxMzA1MDM4MDA2"
"Extrema","MG","MzExMDA1MjI1MTAx"
"Santa Maria da VItoria","BA","MjkwMTAwMzI4MTA5"
"Barra do Pirai","RJ","MzMwNTAxMjAwMzA4"
"Piripiri","PI","MjIwMTAwMTA4NDAz"
"Venda Nova do Imigrante","ES","MzIwMzAwNzA1MDY5"
"Timoteo","MG","MzEwODAzOTY4NzA1"
"Carapicuiba","SP","MzUxNTA1NzEwNjA5"
"Cotia","SP","MzUxNTA2MDEzMDA5"
"Nova Serrana","MG","MzEwOTA0MzQ1MjA4"
"Barra do Corda","MA","MjEwMzAxMTAxNjA4"
"Januaria","MG","MzEwMjAwMzM1MjA5"
"Bebedouro","SP","MzUwMjAxMzA2MTAy"
"Barra Bonita","SP","MzUwNDAyMTA1MzAy"
"Campo Novo do Parecis","MT","NTEwMTAwNDAyNjM3"
"Lagoa Santa","MG","MzEwNzAzMDM3NjAx"
"Valinhos","SP","MzUwNzAzMjU2MjA2"
"Campo Belo","MG","MzEwOTA0NTExMjAw"
"Paraiso do Norte","PR","NDEwMTAwMTE4MDA2"
"Batatais","SP","MzUwMjAxNTA1OTA2"
"Itapetininga","SP","MzUxMTA0MjIyMzA3"
"Caraguatatuba","SP","MzUxMzA1NDEwNTAw"
"Monte Carmelo","MG","MzEwNTAxOTQzMTA0"
"Alto Horizonte","GO","NTIwMjAwNDAwNTU1"
"Propria","SE","MjgwMzAwNzA1NzAz"
"Campo Limpo Paulista","SP","MzUxMjA0NzA5NjAx"
"Timon","MA","MjEwNDAxNzEyMjA5"
"Macae","RJ","MzMwMjAwNDAyNDAz"
"Ituporanga","SC","NDIwNDAxNDA4NTAw"
"Tobias Barreto","SE","MjgwMjAwNTA3NDAy"
"Conceicao do Coite","BA","MjkwNDAxNjA4NDA4"
"Sao Sebastiao","SP","MzUxMzA1NDUwNzA0"
"Capinzal","SC","NDIwMTAwNDAzOTA3"
"Pirassununga","SP","MzUwNzAyOTM5MzAx"
"Rubiataba","GO","NTIwMzAwNjE4OTA0"
"Riachao do Jacuipe","BA","MjkwNDAxNjI2MzAx"
"Campina Grande do Sul","PR","NDExMDAzNzA0MDA2"
"Canoinhas","SC","NDIwMjAwNjAzODA4"
"Caico","RN","MjQwMjAxMTAyMDA2"
"Bom Jesus do Itabapoana","RJ","MzMwMTAwMTAwNjA1"
"Itapira","SP","MzUwNzAzMTIyNjA0"
"Caninde de Sao Francisco","SE","MjgwMTAwMTAxMjA3"
"Sao Gabriel da Palha","ES","MzIwMTAwMjA0NzA4"
"Paulinia","SP","MzUwNzAzMjM2NTA1"
"Mariana","MG","MzEwNzAzMzQwMDAx"
"Itu","SP","MzUxMjA0NjIzOTA5"
"Sobral","CE","MjMwMTAwNTEyOTA4"
"Tapejara","RS","NDMwMTAxMDIwOTA5"
"Remanso","BA","MjkwMjAwNDI2MDA0"
"Itaituba","PA","MTUwNTAxNDAzNjA2"
"Eunapolis","BA","MjkwNzAzMjEwNzI3"
"Costa Rica","MS","NTAwMzAwNTAzMjU2"
"Varzea Grande","MT","NTEwNDAxNzA4NDAy"
"Ananindeua","PA","MTUwMzAwNzAwODAw"
"Taboao da Serra","SP","MzUxNTA2MDUyODA5"
"Braco do Norte","SC","NDIwNjAxODAyODAw"
"Porto Ferreira","SP","MzUwNzAyOTQwNzA1"
"Sao Goncalo do Amarante","CE","MjMwMjAwOTEyNDAz"
"Mundo Novo","MS","NTAwNDAxMTA1Njgx"
"Quissama","RJ","MzMwMjAwNDA0MTUx"
"Paraiso do Tocantins","TO","MTcwMTAwNDE2MTA5"
"Monte Aprazivel","SP","MzUwMTAwNzMxNDA3"
"Arapoti","PR","NDEwNTAyMDAxNjA2"
"Machado","MG","MzExMDA0OTM5MDAz"
"Sao VIcente","SP","MzUxNTA2MzUxMDA5"
"Carangola","MG","MzExMjA2MzEzMzA1"
"Tres Pontas","MG","MzExMDA1MDY5NDA2"
"Ampere","PR","NDEwNzAyNTAxMDAy"
"Indaial","SC","NDIwNDAxMjA3NTAy"
"Ivaipora","PR","NDEwMzAxMzExNTA2"
"Cambe","PR","NDEwMzAxMTAzNzAx"
"Paco do Lumiar","MA","MjEwMTAwMjA3NTA2"
"Itapecerica da Serra","SP","MzUxNTA2MDIyMjA4"
"Novo Gama","GO","NTIwNDAxMjE1MjMx"
"Novo Horizonte","SP","MzUwMTAwODMzNTAy"
"Presidente Venceslau","SP","MzUwODAzNjQxNTA1"
"Rancharia","SP","MzUwODAzNjQyMjA2"
"Ribeirao Pires","SP","MzUxNTA2MTQzMzAz"
"Sertaozinho","SP","MzUwMjAxNDUxNzAy"
"Barcarena","PA","MTUwMzAwNzAxMzAz"
"Garanhuns","PE","MjYwMzAxMTA2MDAy"
"Nazare","BA","MjkwNTAyMDIyNTA4"
"Alpinopolis","MG","MzExMDA0NzAxOTA0"
"Ouro Preto","MG","MzEwNzAzMzQ2MTA3"
"Nova Mutum","MT","NTEwMTAwNjA2MjI0"
"Almeirim","PA","MTUwMTAwMzAwNTAz"
"Altamira","PA","MTUwNTAxNTAwNjAy"
"Salgueiro","PE","MjYwMTAwMjEyMjA4"
"Picos","PI","MjIwNDAxMzA4MDA3"
"Chopinzinho","PR","NDEwNzAyNzA1NDA5"
"Jacarezinho","PR","NDEwNDAxNjExODAz"
"Laranjeiras do Sul","PR","NDEwODAyOTEzMzA0"
"Lobato","PR","NDEwMzAwNjEzNjAx"
"Nova Londrina","PR","NDEwMTAwMTE3MTA3"
"Palmeira","PR","NDEwNTAyMTE3NzAx"
"Paranagua","PR","NDExMDAzODE4MjA0"
"Pien","PR","NDExMDAzOTE5MTAz"
"Prudentopolis","PR","NDEwOTAzMTIwNjA2"
"Quedas do Iguacu","PR","NDEwODAyOTIwOTAz"
"Ubirata","PR","NDEwMjAwNDI4MDA1"
"Marica","RJ","MzMwNjAxODAyNzAw"
"Nova Friburgo","RJ","MzMwMzAwNzAzNDAx"
"Arroio do Tigre","RS","NDMwNDAyMDAxMjA2"
"Itaqui","RS","NDMwNjAyOTEwNjAz"
"Lajeado","RS","NDMwNDAyMTExNDAz"
"Palmeira das Missoes","RS","NDMwMTAwOTEzNzA2"
"Sao Borja","RS","NDMwNjAyOTE4MDAy"
"Herval D"Oeste"","SC","NDIwMTAwNDA2NzAy"
"Sao Lourenco do Oeste","SC","NDIwMTAwMjE2OTA5"
"Itapevi","SP","MzUxNTA1NzIyNTA1"
"Mairipora","SP","MzUxNTA1ODI4NTAy"
"Mogi-Guacu","SP","MzUwNzAzMTMwNzA2"
"Ourinhos","SP","MzUxMDA0MDM0NzA4"
"Sandovalina","SP","MzUwODAzNjQ1NTA2"
"Tatui","SP","MzUxMTA0MzU0MDAz"
"Ubatuba","SP","MzUxMzA1NDU1NDA2"
"Vinhedo","SP","MzUwNzAzMjU2NzAx"
"Gurupi","TO","MTcwMTAwNTA5NTAw"
"Porto Feliz","SP","MzUxMjA0NjQwNjA2"
"Sao Manuel","SP","MzUwNDAyMzUwMTAw"
"Brumado","BA","MjkwNjAyNzA0NjA1"
"Caetite","BA","MjkwNjAyNjA1MjA2"
"Candeias","BA","MjkwNTAyMTA2NTAx"
"Capelinha","MG","MzEwMzAxMTEyMzA3"
"Carmo do Rio Claro","MG","MzExMDA0OTE0NDAy"
"Capanema","PA","MTUwNDAxMDAyMjAy"
"Capanema","PR","NDEwNzAyNTA0NTAx"
"Capitao Leonidas Marques","PR","NDEwNjAyMzA0NjAw"
"Castro","PR","NDEwNTAyMTA0OTA3"
"Cacador","SC","NDIwMTAwNDAzMDA2"
"Jaru","RO","MTEwMjAwNDAwMTE0"
"Nazare da Mata","PE","MjYwNDAxMzA5NTAx"
"Uruguaiana","RS","NDMwNjAyOTIyNDAw"
"Ituiutaba","MG","MzEwNTAxNzM0MjAy"
"Matao","SP","MzUwNTAyNDI5MzAy"
"Piuma","ES","MzIwMzAxMDA0MjAz"
"Astorga","PR","NDEwMzAwNjAyMTA5"
"Santa Fe","PR","NDEwMzAwNjIzNDAy"
"Tramandai","RS","NDMwNTAyNzIxNjAw"
"Teodoro Sampaio","SP","MzUwODAzNjU0MzAw"
"Socorro","SP","MzUwNzAzMzUyMTA2"
"Chapadinha","MA","MjEwNDAxNDAzMjA4"
"Loanda","PR","NDEwMTAwMTEzNTAy"
"Porteirinha","MG","MzEwMjAwNDUyMjA0"
"Itapetinga","BA","MjkwNjAyOTE2NDAx"
"Baependi","MG","MzExMDA1NDA0OTA4"
"Congonhas","MG","MzEwNzAzNDE4MDA3"
"Ipojuca","PE","MjYwNTAxODA3MjA4"
"Itapolis","SP","MzUwNTAyNDIyNzAz"
"Jaragua","GO","NTIwMzAwNzExODAw"
"Canela","RS","NDMwNTAyNDA0NDA4"
"Guapore","RS","NDMwMjAxNDA5NDA3"
"Nova Prata","RS","NDMwMjAxNDEzMzAw"
"Sao Sebastiao do Cai","RS","NDMwNTAyMzE5NTA1"
"Icara","SC","NDIwNjAxOTA3MDA3"
"Sao Lourenco da Mata","PE","MjYwNTAxNzEzNzAx"
"Cabo de Santo Agostinho","PE","MjYwNTAxODAyOTAy"
"Breves","PA","MTUwMjAwNTAxODA4"
"Sao Felix do Coribe","BA","MjkwMTAwMzI5MDU3"
"Seabra","BA","MjkwNjAyMzI5OTA5"
"Conceicao do Araguaia","PA","MTUwNjAyMjAyNzA3"
"Diamantina","MG","MzEwMzAxMDIxNjA1"
"Maracanau","CE","MjMwMzAxNjA3NjUw"
"Itapuranga","GO","NTIwMzAwNjExMjA2"
"Piracanjuba","GO","NTIwNTAxNTE3MTA0"
"Itaberaba","BA","MjkwMzAxMTE0NzAz"
"Palmeira dos Indios","AL","MjcwMjAwNTA2MzA3"
"Rio Verde","GO","NTIwNTAxMzE4ODA1"
"Araxa","MG","MzEwNTAyMzA0MDA3"
"Aquidauana","MS","NTAwMTAwMjAxMTAy"
"Chapadao do Sul","MS","NTAwMzAwNTAyOTUx"
"Coronel Sapucaia","MS","NTAwNDAxMTAzMTU3"
"Miranda","MS","NTAwMTAwMjA1NjA4"
"Navirai","MS","NTAwNDAxMTA1NzA3"
"Alto Araguaia","MT","NTEwNTAyMjAwMzAw"
"Canarana","MT","NTEwMjAxMDAyNzAy"
"Pontes e Lacerda","MT","NTEwMzAxMjA2NzUy"
"Tailandia","PA","MTUwNDAxMjA3OTUz"
"Nova Odessa","SP","MzUwNzAzMjMzNDAz"
"Aracuai","MG","MzEwMzAxMjAzNDA1"
"Coxim","MS","NTAwMjAwMzAzMzA2"
"Nova Andradina","MS","NTAwMzAwODA2MjAw"
"Angra dos Reis","RJ","MzMwNTAxMzAwMTAw"
"Currais Novos","RN","MjQwMjAxMjAzMTAz"
"Penapolis","SP","MzUwMzAxODM3MzA1"
"Itanhaem","SP","MzUxNDA1NjIyMTA5"
"Sao Miguel do Guapore","RO","MTEwMjAwNTAwMzIw"
"Itapipoca","CE","MjMwMjAwODA2NDA1"
"Ibirite","MG","MzEwNzAzMDI5ODA2"
"Novo Cruzeiro","MG","MzEwMzAxMjQ1MzA3"
"Pinhais","PR","NDExMDAzNzE5MTUy"
"Ibiassuce","BA","MjkwNjAyNjEyMDA0"
"Presidente Dutra","MA","MjEwMzAxMjA5MTA2"
"Sacramento","MG","MzEwNTAyMzU2OTA4"
"Irati","PR","NDEwOTAzMjEwNzA2"
"Lapa","PR","NDExMDAzNjEzMjA1"
"Matinhos","PR","NDExMDAzODE1NzA1"
"Palotina","PR","NDEwNjAyMjE3OTA5"
"Piraquara","PR","NDExMDAzNzE5NTA5"
"Rio Negro","PR","NDExMDAzOTIyMzA1"
"Sao Mateus do Sul","PR","NDEwOTAzNDI1NjA1"
"Terra Boa","PR","NDEwMjAwNTI3MjA1"
"Imbe","RS","NDMwNTAyNzEwMzMw"
"Saudades","SC","NDIwMTAwMjE3MzAz"
"Santa Terezinha de Goias","GO","NTIwMjAwNDE5NzA0"
"Lagoa da Prata","MG","MzEwNjAyNjM3MjA1"
"Santa Cruz do Capibaribe","PE","MjYwMzAwOTEyNTA1"
"Parintins","AM","MTMwMzAxMDAzNDAz"
"Pirapora","MG","MzEwMjAwNjUxMjA2"
"Colider","MT","NTEwMTAwMzAzMjA1"
"Assai","PR","NDEwNDAxNDAxOTAz"
"Limoeiro do Norte","CE","MjMwNTAyMzA3NjAx"
"Iguatu","CE","MjMwNjAyNjA1NTA2"
"Iuna","ES","MzIwNDAxMTAzMDA3"
"Lambari","MG","MzExMDA1NDM3ODA5"
"Bom Jesus da Lapa","BA","MjkwMjAwNzAzOTA0"
"Camocim","CE","MjMwMTAwMTAyNjAy"
"Alem Paraiba","MG","MzExMjA2NjAxNTA4"
"Alta Floresta","MT","NTEwMTAwMjAwMjUw"
"Mage","RJ","MzMwNjAxODAyNTAy"
"Gramado","RS","NDMwNTAyNDA5MTAw"
"Portao","RS","NDMwNTAyMzE0ODAz"
"Ipira","BA","MjkwMzAxMjE0MDAw"
"Esplanada","BA","MjkwNDAxODEwNjAy"
"Rosario do Sul","RS","NDMwNjAzMDE2NDAy"
"Porangatu","GO","NTIwMjAwNDE4MDAz"
"Buritis","RO","MTEwMTAwMTAwNDUy"
"Uniao dos Palmares","AL","MjcwMzAwODA5MzAx"
"Maues","AM","MTMwMzAxMDAyOTAw"
"Tefe","AM","MTMwMzAwNTA0MjAz"
"Santo Estevao","BA","MjkwMzAxMjI4ODAy"
"Serrinha","BA","MjkwNDAxNjMwNTAx"
"Santo Antonio do Descoberto","GO","NTIwNDAxMjE5NzUz"
"Senador Canedo","GO","NTIwMzAxMDIwNDU0"
"Barreirinhas","MA","MjEwMTAwNDAxNzA3"
"Santa Ines","MA","MjEwMjAwODA5OTA4"
"Minas Novas","MG","MzEwMzAxMTQxODAx"
"Salinas","MG","MzEwMjAwNTU3MDA1"
"Mirassol D"Oeste"","MT","NTEwMzAxNDA1NjIy"
"Sao Bento do Una","PE","MjYwMzAwODEzMDA4"
"Sarandi","PR","NDEwMzAwOTI2MjU2"
"Cangucu","RS","NDMwNzAzMzA0NTA3"
"Esteio","RS","NDMwNTAyNjA3NzA4"
"Santo Antonio da Patrulha","RS","NDMwNTAyNzE3NjA4"
"Sao Lourenco do Sul","RS","NDMwNzAzMzE4ODA0"
"Sapucaia do Sul","RS","NDMwNTAyNjIwMDA4"
"Veranopolis","RS","NDMwMjAxNjIyODA2"
"Viamao","RS","NDMwNTAyNjIzMDAy"
"Camboriu","SC","NDIwNDAxMzAzMjA0"
"Laguna","SC","NDIwNjAxODA5NDA5"
"Lauro Muller","SC","NDIwNjAxOTA5NjA3"
"Porto Uniao","SC","NDIwMjAwNjEzNjA5"
"Iconha","ES","MzIwMzAxMDAyNjAz"
"Pinheiros","ES","MzIwMjAwNDA0MTA0"
"Engenheiro Caldas","MG","MzEwODAzNzIzNzAw"
"Formiga","MG","MzEwOTA0NDI2MTA5"
"Guanhaes","MG","MzEwODAzNTI4MDA2"
"Joaima","MG","MzEwMzAxNDM2MDA5"
"Oliveira","MG","MzEwOTA0NjQ1NjA0"
"Piumhi","MG","MzEwOTA0MjUxNTAz"
"Cravinhos","SP","MzUwMjAxNDEzMTA4"
"Cubatao","SP","MzUxNTA2MzEzNTA0"
"Franco da Rocha","SP","MzUxNTA1ODE2NDA4"
"Pariquera-Acu","SP","MzUxNDA1NTM2MjA4"
"Salto de Pirapora","SP","MzUxMjA0NjQ1MzA4"
"Santa Rosa de VIterbo","SP","MzUwMjAxNDQ3NjAx"
"Nova Cruz","RN","MjQwMzAxNTA4MzAw"
"Riacho de Santana","BA","MjkwNjAyNjI2NDAw"
"Anchieta","ES","MzIwMzAxMDAwNDA5"
"Barra de Sao Francisco","ES","MzIwMTAwMTAwOTA0"
"Nova Granada","SP","MzUwMTAwNDMzMDA3"
"Conceicao do Jacuipe","BA","MjkwMzAxMjA4NTA3"
"Planaltina","GO","NTIwNDAxMjE3NjA5"
"Ervalia","MG","MzExMjA2MjI0MDA1"
"Passos","MG","MzExMDA0NzQ3OTA3"
"Mococa","SP","MzUwNzAzMDMwNTA4"
"Mogi-Mirim","SP","MzUwNzAzMTMwODA1"
"Monte Alto","SP","MzUwMjAxMzMxMzA4"
"Paranapanema","SP","MzUwNDAyMjM1ODA0"
"Pedreira","SP","MzUwNzAzMjM3MTA3"
"Santa Rita do Passa Quatro","SP","MzUwMjAxNDQ3NTAy"
"Sao Joaquim da Barra","SP","MzUwMjAxMDQ5NDA5"
"Sampaio","TO","MTcwMTAwMTE4ODA4"
"Alvorada","RS","NDMwNTAyNjAwNjA0"
"Roncador","PR","NDEwMjAwNTIyNTAz"
"Nilopolis","RJ","MzMwNjAxODAzMjAz"
"Afonso Claudio","ES","MzIwMzAwNzAwMTAy"
"Baturite","CE","MjMwMjAxMzAyMTA3"
"Prata","MG","MzEwNTAxODUyODA4"
"Belford Roxo","RJ","MzMwNjAxODAwNDU2"
"Santa Adelia","SP","MzUwMTAwNTQ1NjA1"
"Caldas Novas","GO","NTIwNTAxNTA0NTA4"
"Capao da Canoa","RS","NDMwNTAyNzA0NjMw"
"Picarras","SC","NDIwNDAxMzEyODA5"
"Itanhandu","MG","MzExMDA1NDMzMTA1"
"Guimarania","MG","MzEwNTAyMDI4OTA3"
"Barbosa Ferraz","PR","NDEwMjAwNTAyNTA1"
"Goioere","PR","NDEwMjAwNDA4NjAx"
"Porecatu","PR","NDEwMzAwNzIwMDAy"
"Terra Rica","PR","NDEwMTAwMTI3MzA0"
"Imbituba","SC","NDIwNjAxODA3MzA0"
"Orlandia","SP","MzUwMjAxMDM0MzAy"
"Faxinal do Soturno","RS","NDMwMzAxOTA4MDAz"
"Santa Barbara","MG","MzEwNzAzMTU3MjAz"
"Iaras","SP","MzUwNDAyMjE5MjUz"
"Santo Amaro","BA","MjkwNTAyMDI4NjA0"
"Agua Boa","MT","NTEwMjAxMDAwMjAx"
"Wenceslau Braz","PR","NDEwNDAxODI4NTAw"
"Porto Seguro","BA","MjkwNzAzMjI1MzAz"
"Sao Felix do XIngu","PA","MTUwNjAxODA3MzAw"
"Bom Jesus","PI","MjIwMzAxMDAxOTAz"
"Curiuva","PR","NDEwNDAxNzA3MDA5"
"Ortigueira","PR","NDEwNTAxOTE3MzA1"
"Tibagi","PR","NDEwNTAxOTI3NTAy"
"Dracena","SP","MzUwODAzNDE0NDAz"
"Jatai","GO","NTIwNTAxMzExOTA5"
"Campo Verde","MT","NTEwNTAxOTAyNjc4"
"Cameta","PA","MTUwNDAxMTAyMTAz"
"Capitao Poco","PA","MTUwNDAxMzAyMzAx"
"Itaquaquecetuba","SP","MzUxNTA2MjIzMTA3"
"Martinopolis","SP","MzUwODAzNjI5MjAz"
"Uruacu","GO","NTIwMjAwNDIxNjAx"
"Andradas","MG","MzExMDA1MTAyNjA1"
"Sapezal","MT","NTEwMTAwNDA3ODc1"
"Ulianopolis","PA","MTUwNjAxNzA4MTI2"
"Sousa","PB","MjUwMTAwMzE2MjAx"
"Araripina","PE","MjYwMTAwMTAxMTAy"
"Arcoverde","PE","MjYwMTAwNDAxMjAx"
"Parati","RJ","MzMwNTAxMzAzODA3"
"Catu","BA","MjkwNTAxOTA3NTA5"
"Marco","CE","MjMwMTAwMTA3ODA5"
"Pedreiras","MA","MjEwMzAxMDA4MjA3"
"Abaete","MG","MzEwNjAyNDAwMjAz"
"Timbauba","PE","MjYwNDAxMzE1MzAw"
"Paracambi","RJ","MzMwNjAxNDAzNjA5"
"Rio Bonito","RJ","MzMwNjAxNjA0MzAw"
"Rio das Ostras","RJ","MzMwNDAwOTA0NTI0"
"Sao Pedro da Aldeia","RJ","MzMwNDAxMDA1MjA4"
"Arroio dos Ratos","RS","NDMwNTAyNTAxMTA3"
"Butia","RS","NDMwNTAyNTAyNzA5"
"Charqueadas","RS","NDMwNTAyNTA1MzU1"
"Estancia Velha","RS","NDMwNTAyNjA3NjA5"
"Nova Petropolis","RS","NDMwNTAyNDEzMjAx"
"Teutonia","RS","NDMwNDAyMTIxNDUx"
"Caiaponia","GO","NTIwNTAxMzA0NDA5"
"Manga","MG","MzEwMjAwMzM5MzAw"
"Rio Verde de Mato Grosso","MS","NTAwMjAwMzA3NDA2"
"Xinguara","PA","MTUwNjAyMTA4NDA3"
"Palmares","PE","MjYwNDAxNTEwMDA0"
"Sao Carlos","SC","NDIwMTAwMjE2MDA4"
"Jurua","AM","MTMwMjAwNDAyMjA3"
"Posse","GO","NTIwNDAxMTE4MzAw"
"Viseu","PA","MTUwNDAxMzA4MzA4"
"Cruzeiro do Sul","AC","MTIwMTAwMTAwMjAz"
"Tabatinga","AM","MTMwMjAwMzA0MDYy"
"Simoes Filho","BA","MjkwNTAyMTMwNzA5"
"Rio Bananal","ES","MzIwMjAwNjA0MzUx"
"Silvania","GO","NTIwNTAxNjIwNjAz"
"Brejo","MA","MjEwNDAxNDAyMTAx"
"Tres Marias","MG","MzEwNjAyNDY5MzU2"
"Bodoquena","MS","NTAwNDAwOTAyMTU5"
"Maracaju","MS","NTAwNDAxMDA1NDAw"
"Colniza","MT","NTEwMTAwMTAzMjU0"
"Juruena","MT","NTEwMTAwMTA1MTc2"
"Costa Marques","RO","MTEwMTAwMjAwMDgw"
"Nova Mamore","RO","MTEwMTAwMTAwMzM4"
"Salto do Jacui","RS","NDMwMTAxMTE2NDUx"
"Santa VItoria do Palmar","RS","NDMwNzAzNTE3MzAx"
"Tres Coroas","RS","NDMwNTAyNDIxNzA5"
"Ipora do Oeste","SC","NDIwMTAwMTA3NjUw"
"Sao Joao Batista","SC","NDIwNTAxNTE2MzA1"
"Conchas","SP","MzUwNDAyMzEyMzA4"
"Poa","SP","MzUxNTA2MjM5ODA2"
"Tiete","SP","MzUwNjAyODU0NTA4"
"Olho D"Agua das Flores"","AL","MjcwMTAwNDA1NzA1"
"Coari","AM","MTMwMzAwNjAxMjA5"
"Barra","BA","MjkwMjAwNjAyNzA4"
"Livramento de Nossa Senhora","BA","MjkwNjAyNTE5NTA0"
"Santaluz","BA","MjkwNDAxNjI4MDAw"
"Morrinhos","GO","NTIwNTAxNTEzODA2"
"Areado","MG","MzExMDA0OTA0MzA0"
"Cassilandia","MS","NTAwMzAwNTAyOTAy"
"Iguatemi","MS","NTAwNDAxMTA0MzA0"
"Nioaque","MS","NTAwNDAwOTA1ODA2"
"Sidrolandia","MS","NTAwMjAwNDA3OTAx"
"Siqueira Campos","PR","NDEwNDAxODI2NjAz"
"Quilombo","SC","NDIwMTAwMjE0MjAx"
"Artur Nogueira","SP","MzUwNzAzMTAzODAy"
"Aruja","SP","MzUxNTA1OTAzOTAx"
"Bertioga","SP","MzUxNTA2MzA2MzU5"
"Cosmopolis","SP","MzUwNzAzMjEyODAz"
"Ferraz de Vasconcelos","SP","MzUxNTA2MjE1NzA3"
"Ibitinga","SP","MzUwNTAyNDE5NjAw"
"Monte Mor","SP","MzUwNzAzMjMxODAz"
"Nhandeara","SP","MzUwMTAwNzMyNjAz"
"Paraguacu Paulista","SP","MzUxMDAzOTM1NTA3"
"Potirendaba","SP","MzUwMTAwNDQwODA0"
"Ribeirao Bonito","SP","MzUwNTAyNTQyOTA5"
"Santa Fe do Sul","SP","MzUwMTAwMTQ2NjAz"
"Serra Negra","SP","MzUwNzAzMzUxNjAz"
"Dianopolis","TO","MTcwMjAwODA3MDA5"
"Monte Alegre de Sergipe","SE","MjgwMTAwMTA0MjAx"
"Neopolis","SE","MjgwMzAwNzA0NDA5"
"Nossa Senhora da Gloria","SE","MjgwMTAwMTA0NTA4"
"Nossa Senhora das Dores","SE","MjgwMjAwMzA0NjA3"
"Nossa Senhora do Socorro","SE","MjgwMzAxMTA0ODA1"
"Poco Verde","SE","MjgwMjAwNTA1NTA1"
"Umbauba","SE","MjgwMzAxMjA3NjAw"
"Tome-Acu","PA","MTUwNDAxMjA4MDAx"
"Ituacu","BA","MjkwNjAyNzE3MjAx"
"Mucuge","BA","MjkwNjAyMzIxOTA2"
"Rio Real","BA","MjkwNDAxNzI3MDAy"
"Acrelandia","AC","MTIwMjAwNDAwMDEz"
"Brasileia","AC","MTIwMjAwNTAwMTA0"
"Morro do Chapeu","BA","MjkwMzAxMDIxNzA4"
"Campina Verde","MG","MzEwNTAyMTExMTAx"
"Carlos Chagas","MG","MzEwNDAxNjEzNzAx"
"Espinosa","MG","MzEwMjAwNDI0MzAy"
"Manhumirim","MG","MzExMjA2MTM5NTA4"
"Ribeirao das Neves","MG","MzEwNzAzMDU0NjA2"
"Sao Goncalo do Sapucai","MG","MzExMDA1MzYyMDA1"
"Tres Coracoes","MG","MzExMDA1MDY5MzA3"
"Amambai","MS","NTAwNDAxMDAwNjA5"
"Eldorado","MS","NTAwNDAxMTAzNzUx"
"Sete Quedas","MS","NTAwNDAxMTA3NzAz"
"Oriximina","PA","MTUwMTAwMTA1MzA0"
"Altonia","PR","NDEwMTAwMjAwNTA5"
"Coronel VIvida","PR","NDEwNzAyNzA2NTA2"
"Itaipulandia","PR","NDEwNjAyNDEwOTUz"
"Acu","RN","MjQwMTAwNDAwMjA4"
"Machadinho D"Oeste"","RO","MTEwMjAwMzAwMTMw"
"Crissiumal","RS","NDMwMTAwMjA2MDA3"
"Adamantina","SP","MzUwODAzNTAwMTA1"
"Aguai","SP","MzUwNzAyOTAwMzAz"
"Aguas de Lindoia","SP","MzUwNzAzMzAwNTAx"
"Biritiba-Mirim","SP","MzUxNTA2MjA2NjA3"
"Cachoeira Paulista","SP","MzUxMzA1MTA4NjAz"
"Candido Mota","SP","MzUxMDAzOTEwMDA1"
"Casa Branca","SP","MzUwNzAzMDEwODA3"
"Charqueada","SP","MzUwNjAyODExNzA2"
"Cruzeiro","SP","MzUxMzA1MTEzNDA1"
"Ibate","SP","MzUwNTAyNTE5MzAz"
"Iguape","SP","MzUxNDA1NTIwMzAx"
"Itajobi","SP","MzUwMTAwODIxOTAz"
"Itaporanga","SP","MzUxMTA0MTIyODAy"
"Jardinopolis","SP","MzUwMjAxNDI1MTAy"
"Joanopolis","SP","MzUxMjA0ODI1NTA4"
"Miguelopolis","SP","MzUwMjAxMDI5NzA4"
"Palmital","SP","MzUxMDAzOTM1MzA5"
"Piraju","SP","MzUxMDA0MDM4ODA4"
"Pirajui","SP","MzUwNDAyMDM4OTA3"
"Regente Feijo","SP","MzUwODAzNjQyNDA0"
"Santa Cruz das Palmeiras","SP","MzUwNzAyOTQ2MzA2"
"Sao Pedro","SP","MzUwNjAyODUwNDA3"
"Tabatinga","SP","MzUwNTAyNDUyNzAw"
"Varzea Paulista","SP","MzUxMjA0NzU2NTAz"
"Iranduba","AM","MTMwMzAwNzAxODUy"
"Itacoatiara","AM","MTMwMzAwOTAxOTAy"
"Manacapuru","AM","MTMwMzAwNzAyNTA0"
"Presidente Figueiredo","AM","MTMwMzAwODAzNTM2"
"Santana","AP","MTYwMjAwMzAwNjAw"
"Domingos Martins","ES","MzIwMzAwNzAxOTAy"
"Fundao","ES","MzIwMjAwNjAyMjA3"
"Berilo","MG","MzEwMzAxMTA2NTA3"
"Marcelandia","MT","NTEwMTAwNzA1NTgw"
"Abaetetuba","PA","MTUwNDAxMTAwMTA3"
"Braganca","PA","MTUwNDAxMDAxNzA5"
"Goianesia do Para","PA","MTUwNjAxNzAzMDkz"
"Aguas Belas","PE","MjYwMzAwNzAwNTAw"
"Belo Jardim","PE","MjYwMzAwODAxNzA2"
"Canhotinho","PE","MjYwMzAxMTAzNzAy"
"Lajedo","PE","MjYwMzAxMTA4ODAw"
"Agua Branca","PI","MjIwMjAwNTAwMjAy"
"Barras","PI","MjIwMTAwMTAxMjAw"
"Sao Raimundo Nonato","PI","MjIwMzAxMTEwNjA3"
"Camaqua","RS","NDMwNTAyODAzNTA5"
"Erval Seco","RS","NDMwMTAwMzA3MzAy"
"Fontoura Xavier","RS","NDMwMTAxMzA4MzAw"
"Agrolandia","SC","NDIwNDAxNDAwMjAw"
"Alfredo Wagner","SC","NDIwNTAxNzAwNzA1"
"Campo Ere","SC","NDIwMTAwMjAzNTAx"
"Fraiburgo","SC","NDIwMTAwNDA1NTA2"
"Gaspar","SC","NDIwNDAxMjA1OTAy"
"Mafra","SC","NDIwMjAwNjEwMTAw"
"Santo Amaro da Imperatriz","SC","NDIwNTAxNjE1NzAz"
"Peixoto de Azevedo","MT","NTEwMTAwMzA2NDIy"
"Junqueiro","AL","MjcwMzAxMjA0MDA1"
"Sao Miguel dos Campos","AL","MjcwMzAxMjA4NjAw"
"Oiapoque","AP","MTYwMTAwMTAwNTAx"
"Itiuba","BA","MjkwMzAwODE3MDAz"
"Monte Santo","BA","MjkwNDAxNDIxNTAw"
"Goiatuba","GO","NTIwNTAxNTA5MTAx"
"Ipameri","GO","NTIwNTAxNzEwMTA5"
"Itaberai","GO","NTIwMzAwNzEwNDA2"
"Palmeiras de Goias","GO","NTIwNTAxNDE1NzAy"
"Sao Joao D"Alianca"","GO","NTIwMjAwNTIwMDA5"
"Grajau","MA","MjEwMzAxMTA0ODAw"
"Boa Esperanca","MG","MzExMDA1MDA3MTA5"
"Bocaiuva","MG","MzEwMjAwOTA3MzA3"
"Jacutinga","MG","MzExMDA1MTM0OTA1"
"Jaiba","MG","MzEwMjAwNDM1MDUw"
"Monte Siao","MG","MzExMDA1MTQzNDAx"
"Paraisopolis","MG","MzExMDA1NjQ3MzAz"
"Sao Francisco","MG","MzEwMjAwMzYxMTA2"
"Nova Xavantina","MT","NTEwMjAxMDA2MjU3"
"Querencia","MT","NTEwMjAxMDA3MDY1"
"Sao Felix do Araguaia","MT","NTEwMjAwOTA3ODU5"
"Tabapora","MT","NTEwMTAwNTA3OTQx"
"Jacunda","PA","MTUwNjAxNjAzODA0"
"Antonina","PR","NDExMDAzODAxMjAw"
"Colorado","PR","NDEwMzAwNjA1OTA0"
"Guaraquecaba","PR","NDExMDAzODA5NTAw"
"Mandirituba","PR","NDExMDAzNzE0MzAy"
"Palmital","PR","NDEwODAyODE3ODAw"
"Quitandinha","PR","NDExMDAzOTIxMjA4"
"Rio Branco do Sul","PR","NDExMDAzNzIyMjA2"
"Santa Helena","PR","NDEwNjAyMjIzNTAx"
"Santo Antonio do Sudoeste","PR","NDEwNzAyNjI0NDAw"
"Apodi","RN","MjQwMTAwMjAxMDA4"
"Guajara-Mirim","RO","MTEwMTAwMjAwMTA2"
"Espumoso","RS","NDMwMTAxMTA3NTAw"
"Nonoai","RS","NDMwMTAwMzEyNzA4"
"Porto Xavier","RS","NDMwMTAwNjE1MTA3"
"Taquara","RS","NDMwNTAyNDIxMjA0"
"Abelardo Luz","SC","NDIwMTAwMzAwMTAx"
"Itapoa","SC","NDIwMjAwODA4NDUw"
"Palma Sola","SC","NDIwMTAwMTEyMDA3"
"Palmitos","SC","NDIwMTAwMjEyMTA2"
"Sombrio","SC","NDIwNjAyMDE3NzA5"
"Embu-Guacu","SP","MzUxNTA2MDE1MTAz"
"Pederneiras","SP","MzUwNDAyMTM2NzAz"
"Alvorada","TO","MTcwMTAwNTAwNzA3"
"Delmiro Gouveia","AL","MjcwMTAwMjAyNDA1"
"Cacule","BA","MjkwNjAyNjA1MDA4"
"Campo Formoso","BA","MjkwMzAwODA2MDA2"
"Condeuba","BA","MjkwNjAyNzA4NzA1"
"Macaubas","BA","MjkwNjAyMjE5ODAx"
"Tanque Novo","BA","MjkwNjAyMjMxMDUz"
"Carmo do Paranaiba","MG","MzEwNTAyMDE0MzAz"
"Porto dos Gauchos","MT","NTEwMTAwNTA2ODAy"
"Rondon do Para","PA","MTUwNjAxNzA2MTg3"
"Campo Magro","PR","NDExMDAzNzA0MjUz"
"Ipora","PR","NDEwMTAwMjEwNjA3"
"Iretama","PR","NDEwMjAwNTEwODA1"
"Mangueirinha","PR","NDEwODAzMDE0NDAx"
"Realeza","PR","NDEwNzAyNTIxNDA2"
"Santa Terezinha de Itaipu","PR","NDEwNjAyNDI0MDUz"
"Sao Pedro do IVai","PR","NDEwMzAxMzI1ODAz"
"Cacapava do Sul","RS","NDMwNzAzMjAyODA4"
"Campo Novo","RS","NDMwMTAwMjA0MDAy"
"Sao Sepe","RS","NDMwMzAxODE5NjA0"
"Garuva","SC","NDIwMjAwODA1ODAz"
"Irani","SC","NDIwMTAwNTA3ODA5"
"Rio Negrinho","SC","NDIwMjAwNzE1MDAw"
"Cabreuva","SP","MzUxMjA0NjA4NDA1"
"Cajamar","SP","MzUxNTA1NzA5MjA1"
"Ibiuna","SP","MzUxMjA0NTE5NzA5"
"Ilhabela","SP","MzUxMzA1NDIwNDAw"
"Jarinu","SP","MzUxMjA0ODI1MjAx"
"Araci","BA","MjkwNDAxNjAyMTA0"
"Camamu","BA","MjkwNzAzMDA1ODAw"
"Dias D"Avila"","BA","MjkwNTAyMTEwMDU3"
"Mata de Sao Joao","BA","MjkwNTAxOTIxMDA1"
"Mundo Novo","BA","MjkwMzAxMTIyMTAy"
"Santa Barbara","BA","MjkwMzAxMjI3NTA3"
"Sao Sebastiao do Passe","BA","MjkwNTAxOTI5NTAz"
"Valente","BA","MjkwNDAxNjMzMDAw"
"Breu Branco","PA","MTUwNjAxNjAxNzgy"
"Mae do Rio","PA","MTUwNDAxMzA0MDU5"
"Portel","PA","MTUwMjAwNDA1ODA5"
"Mairinque","SP","MzUxMjA0NjI4NDAz"
"Poxoreo","MT","NTEwNTAyMDA3MDA4"
"Urucui","PI","MjIwMzAwNzExMjA5"
"Caldeirao Grande","BA","MjkwMzAxMDA1NTAz"
"Formosa do Rio Preto","BA","MjkwMTAwMTExMTA1"
"Itamaraju","BA","MjkwNzAzMjE1NjAx"
"Jaguaquara","BA","MjkwNjAyNDE3NjA3"
"Ruy Barbosa","BA","MjkwMzAxMTI3MjAw"
"Utinga","BA","MjkwNjAyMzMyODA0"
"Xique-Xique","BA","MjkwMjAwNjMzNjA0"
"Taua","CE","MjMwNDAyMDEzMzAy"
"Niquelandia","GO","NTIwMjAwNDE0NjA2"
"Acailandia","MA","MjEwMjAwOTAwMDU1"
"Brasilia de Minas","MG","MzEwMjAwNzA4NjAy"
"Itacarambi","MG","MzEwMjAwMzMyMTA3"
"Itaquirai","MS","NTAwNDAxMTA0NjAx"
"Paranaiba","MS","NTAwMzAwNjA2MzA5"
"Paranhos","MS","NTAwNDAxMTA2MzU4"
"Gravata","PE","MjYwMzAwODA2NDA4"
"Pesqueira","PE","MjYwMzAwODEwOTA1"
"Palmas","PR","NDEwODAzMDE3NjAy"
"Porto Real","RJ","MzMwNTAxMTA0MTEw"
"Sao Joao de Meriti","RJ","MzMwNjAxODA1MTA5"
"Ibiruba","RS","NDMwMTAxMTEwMDA5"
"Sao Pedro do Sul","RS","NDMwMzAxODE5NDA2"
"Pojuca","BA","MjkwNTAxOTI1MjA0"
"Eldorado dos Carajas","PA","MTUwNjAxOTAyOTU0"
"Euclides da Cunha","BA","MjkwNDAxNDEwNzAx"
"Acarau","CE","MjMwMTAwMTAwMjAw"
"Sao Miguel do Araguaia","GO","NTIwMTAwMTIwMjA3"
"Porto Alegre do Norte","MT","NTEwMjAwOTA2Nzc4"
"Catole do Rocha","PB","MjUwMTAwMTA0MzA2"
"Pianco","PB","MjUwMTAwNTExMzAx"
"Afogados da Ingazeira","PE","MjYwMTAwMzAwMTA0"
"Faxinal","PR","NDEwMzAxMjA3NjAz"
"Manoel Ribas","PR","NDEwMzAxMzE0NTAw"
"Catanduvas","SC","NDIwMTAwNDA0MDA0"
"Gandu","BA","MjkwNzAzMTExMjA0"
"Maracas","BA","MjkwNjAyNDIwNTAy"
"Presidente Bernardes","SP","MzUwODAzNjQxMjA4"
"Sao Roque de Minas","MG","MzEwOTA0MjY0MzA4"
"Vere","PR","NDEwNzAyNjI4NjA5"
"Joao Dourado","BA","MjkwMzAwOTE4MzU3"
"Barbalha","CE","MjMwNzAzMjAxOTAx"
"Nova Olinda do Maranhao","MA","MjEwMjAwODA3MzU3"
"Taiobeiras","MG","MzEwMjAwNTY4MDAy"
"Varzea da Palma","MG","MzEwMjAwNjcwODAw"
"Ivinhema","MS","NTAwNDAxMTA0NzAw"
"Campo Maior","PI","MjIwMjAwNDAyMjA4"
"Esperantina","PI","MjIwMTAwMTAzNzAx"
"Joao Camara","RN","MjQwMzAxMzA1ODAx"
"Murici","AL","MjcwMzAwOTA1NTA3"
"Ibotirama","BA","MjkwMjAwNjEzMjAw"
"Caninde","CE","MjMwMjAxMjAyODAw"
"Cidade Ocidental","GO","NTIwNDAxMjA1NDk3"
"Colinas","MA","MjEwNDAxODAzNTA1"
"Mantena","MG","MzEwODAzODM5NjA3"
"Medina","MG","MzEwMzAxMzQxNDA1"
"Camapua","MS","NTAwMjAwMzAyNjA1"
"Jardim","MS","NTAwNDAwOTA1MDA0"
"Sao Gabriel do Oeste","MS","NTAwMjAwMzA3Njk1"
"Carpina","PE","MjYwNDAxMzA0MDA3"
"Itaguai","RJ","MzMwNjAxNzAyMDA3"
"Santa Cruz do Rio Pardo","SP","MzUxMDA0MDQ2NDA1"
"Sena Madureira","AC","MTIwMjAwMzAwNTAw"
"Belmonte","BA","MjkwNzAzMTAzNDA5"
"Campos Belos","GO","NTIwMjAwNTA0OTA0"
"Ijaci","MG","MzExMTA1NzMwNDA4"
"Antonio Joao","MS","NTAwNDAxMDAwOTA2"
"Aral Moreira","MS","NTAwNDAxMDAxMjQz"
"Bataguassu","MS","NTAwMzAwODAxOTA0"
"Bela VIsta","MS","NTAwNDAwOTAyMTAw"
"Bonito","MS","NTAwNDAwOTAyMjA5"
"Caracol","MS","NTAwNDAwOTAyODAz"
"Deodapolis","MS","NTAwNDAxMTAzNDU0"
"Jatei","MS","NTAwNDAxMTA1MTAz"
"Rio Brilhante","MS","NTAwNDAxMDA3MjA4"
"Sonora","MS","NTAwMjAwMzA3OTM1"
"Tacuru","MS","NTAwNDAxMTA3OTUw"
"Ourilandia do Norte","PA","MTUwNjAxODA1NDM3"
"Anahy","PR","NDEwNjAyMzAxMDUx"
"Andira","PR","NDEwNDAxNTAxMTAx"
"Campina da Lagoa","PR","NDEwMjAwNDAzOTA5"
"Catanduvas","PR","NDEwNjAyMzA1MDAz"
"Leopolis","PR","NDEwNDAxNTEzNDAz"
"Nova Santa Barbara","PR","NDEwNDAxNDE3MjE0"
"Rio Bonito do Iguacu","PR","NDEwODAyOTIyMTU2"
"Arroio Grande","RS","NDMwNzAzNDAxMzA1"
"Igrejinha","RS","NDMwNTAyNDEwMTA4"
"Barra Velha","SC","NDIwNDAxMzAyMTA3"
"Frei Rogério","SC","NDIwMzAwOTA1NTU1"
"Altinopolis","SP","MzUwMjAxNTAxMDA0"
"Chavantes","SP","MzUxMDA0MDU3MjA0"
"Igarapava","SP","MzUwMjAxMTIwMTAz"
"Coruripe","AL","MjcwMzAxMjAyMzA2"
"Encruzilhada","BA","MjkwNjAyOTEwNDA0"
"Jacaraci","BA","MjkwNjAyNjE3NDA5"
"Alexania","GO","NTIwNDAxMjAwMzA4"
"Parnarama","MA","MjEwNDAxNzA3ODAz"
"Corguinho","MS","NTAwMjAwNDAzMTA4"
"Icaraima","PR","NDEwMTAwMjA5OTA2"
"Jardim Alegre","PR","NDEwMzAxMzEyNTA0"
"Rosario do IVai","PR","NDEwMzAxMzIyNjUx"
"Tamboara","PR","NDEwMTAwMTI2NzAy"
"Goianinha","RN","MjQwNDAxOTA0MjAw"
"Jaguarao","RS","NDMwNzAzNDExMDA3"
"Santa Barbara do Sul","RS","NDMwMTAxMTE2NzA5"
"Lagoa da Confusao","TO","MTcwMTAwNDExOTAy"
"Serra do Ramalho","BA","MjkwMjAwNzMwMTU0"
"Marilandia","ES","MzIwMTAwMzAzMzUz"
"Arinos","MG","MzEwMTAwMTA0NTAy"
"Caete","MG","MzEwNzAzMDEwMDA0"
"Rio Pardo de Minas","MG","MzEwMjAwNTU1NjAz"
"Sao Joao do Paraiso","MG","MzEwMjAwNTYyNzA4"
"Ribas do Rio Pardo","MS","NTAwMzAwNzA3MTA5"
"Benevides","PA","MTUwMzAwNzAxNTAx"
"Cerejeiras","RO","MTEwMjAwODAwMDU2"
"Cacequi","RS","NDMwMzAxODAyOTA3"
"Guaramirim","SC","NDIwMjAwODA2NTA0"
"Pilar do Sul","SP","MzUxMjA0NTM3OTA5"
"Rio Pomba","MG","MzExMjA2NDU1ODAx"
"Jandaia do Sul","PR","NDEwMzAxMDEyMTA4"
"Cocos","BA","MjkwMTAwMzA4MTAx"
"Tupancireta","RS","NDMwMzAxNzIyMjAy"
"Capela do Alto","SP","MzUxMjA0NjEwMzAy"
"Sao Paulo das Missoes","RS","NDMwMTAwNjE5MzA3"
"Canto do Buriti","PI","MjIwMzAxMTAyMzA3"
"Tarauaca","AC","MTIwMTAwMjAwNjA5"
"Ibicoara","BA","MjkwNjAyMzEyMjAy"
"Andradina","SP","MzUwMzAxNjAyMTAx"
"Guaira","SP","MzUwMjAxMDE3NDA2"
"Feijo","AC","MTIwMTAwMjAwMzAy"
"Abaira","BA","MjkwNjAyMzAwMTA4"
"Baixa Grande","BA","MjkwMzAxMTAyNjA5"
"Barra do Mendes","BA","MjkwMzAwOTAzMDAz"
"Brotas de Macaubas","BA","MjkwNjAyMjA0NTA2"
"Capim Grosso","BA","MjkwMzAxMDA2ODcz"
"Miguel Calmon","BA","MjkwMzAxMDIxMjAz"
"Pocoes","BA","MjkwNjAyODI1MTA1"
"Passa Quatro","MG","MzExMDA1NDQ3NjAw"
"Barra do Bugres","MT","NTEwMzAxMzAxNzA0"
"Bayeux","PB","MjUwNDAyMjAxODA3"
"Alta Floresta D Oeste","RO","MTEwMjAwNjAwMDE1"
"Aparecida","SP","MzUxMzA1MTAyNTA3"
"Aracoiaba da Serra","SP","MzUxMjA0NjAyOTAz"
"Clementina","SP","MzUwMzAxODExOTA0"
"Cordeiropolis","SP","MzUwNjAyNzEyNDA3"
"Florida Paulista","SP","MzUwODAzNTE2MDAy"
"General Salgado","SP","MzUwMTAwNjE2OTAz"
"Lucelia","SP","MzUwODAzNTI3NDA1"
"Mirante do Paranapanema","SP","MzUwODAzNjMwMjAx"
"Piacatu","SP","MzUwMzAxODM3NzAx"
"Promissao","SP","MzUwNDAxOTQxNjA0"
"Santo Anastacio","SP","MzUwODAzNjQ3NzAw"
"Valparaiso","SP","MzUwMzAxNzU2MzA1"
"Lago da Pedra","MA","MjEwMjAwODA1NzA4"
"Marataizes","ES","MzIwNDAxMzAzMzIw"
"Itaporanga","PB","MjUwMTAwNjA3MDAy"
